# Copyright (c) Fantasy Card Battle. All rights reserved.
#
# Tools/card_catalog.py - the authored content: 110 cards across 10 factions.
#
# This module is DATA, not code. Rules:
#   * `stats` may pin any of age / power / speed / height (cm). Anything left out is derived from the
#     archetype band + rarity band, then jittered deterministically by Tools/generate_cards.py.
#   * Flat ability bonuses (FlatBonusOnAttribute) may only target Power or Speed. Every other numeric
#     effect is a percent so it stays meaningful on Age (up to 999999) and Height (up to 90 m).
#   * Rarity budget per faction: 4 Common, 3 Uncommon, 2 Rare, 1 Epic, 1 Legendary (11 cards).

# faction key -> (display name, enum, doctrine name, bonus attr, bonus %, penalty attr, penalty %, frame colour, lore)
FACTIONS = [
    ("dragonkind", "Dragonkind", "Dragonkind", "Wyrmskin", "Power", 8, "Speed", -6, "#B4361F",
     "Elders of the sky-hoards; they remember every war and forgive none of them."),
    ("arcane", "Arcane Orders", "ArcaneOrders", "Spellshift", "Age", 18, "Power", -3, "#4C6FD1",
     "Colleges, covens and familiars. Time bends around a wizard who has outlived their own school."),
    ("blade", "Order of the Blade", "OrderOfTheBlade", "Oathbound", "Speed", 6, "Height", -4, "#C9A227",
     "Knightly houses bound by sworn oaths; the oath outlives the knight and keeps their banners moving."),
    ("ironhold", "Ironhold", "Ironhold", "Deepforged", "Height", 13, "Speed", -4, "#7C6A4E",
     "Dwarven holds and their forge-titans. Slow, immovable, offended."),
    ("fey", "Fey Court", "FeyCourt", "Feylight", "Speed", 8, "Power", -6, "#3FA36B",
     "The Gentry: beautiful, contractual, and always counting the favours you owe."),
    ("undying", "Undying Legion", "UndyingLegion", "Deathless", "Age", 30, "Speed", -2, "#6B7A8F",
     "Liches, wights and bone-choirs. Nobody out-ages a corpse that stopped keeping score."),
    ("abyss", "Abyssal Horde", "AbyssalHorde", "Hellmark", "Power", 7, "Age", -10, "#8A1F3C",
     "Contract demons and their beasts. Every one of them is late for something awful."),
    ("celestial", "Celestial Host", "CelestialHost", "Ascendant", "Height", 8, "Power", -4, "#D9C77A",
     "Seraphs, colossi and elementals of the upper spheres - tall orders, tall statues."),
    ("beastwild", "Beastwild", "Beastwild", "Untamed", "Speed", 9, "Height", -7, "#5A7D3A",
     "Orcs, goblins, werewolves and everything the frontier names with a shout."),
    ("deepwater", "Deepwater Court", "DeepwaterCourt", "Tidebound", "Age", 9, "Power", -4, "#2C7C93",
     "Leviathans, merrow and drowned kings. The pressure down there keeps things young and very, very old."),
]

# rarity -> (power base, speed base, age base years, height base cm)
RARITY_BAND = {
    "Common":    (46, 52, 45, 180),
    "Uncommon":  (55, 58, 80, 205),
    "Rare":      (66, 64, 150, 235),
    "Epic":      (78, 70, 400, 270),
    "Legendary": (92, 76, 900, 310),
    "Mythic":    (108, 82, 3000, 400),
}

# archetype -> (power mult, speed mult, age mult, height mult)
ARCHETYPES = {
    "brute":    (1.28, 0.72, 1.00, 1.05),
    "titan":    (1.18, 0.45, 1.45, 2.90),
    "swift":    (0.82, 1.32, 0.85, 0.78),
    "elder":    (0.98, 0.62, 6.50, 1.10),
    "caster":   (1.02, 0.88, 2.40, 0.95),
    "vermin":   (0.52, 1.18, 0.55, 0.26),
    "balanced": (1.00, 1.00, 1.00, 1.00),
    "undead":   (1.00, 0.92, 5.20, 1.00),
    "holy":     (1.06, 1.02, 1.70, 1.20),
    "beast":    (1.12, 1.16, 0.70, 0.88),
    "horde":    (0.90, 1.05, 0.90, 0.92),
}

# ability id -> definition. `min` is the lowest rarity allowed to carry it (engine validator agrees).
ABILITIES = {
    "EmberFury":      dict(effect="FlatBonusOnAttribute", attribute="Power", a=9, b=0, min="Rare",
                           name="Ember Fury", desc="When Power is contested, add +9."),
    "Stormstride":    dict(effect="FlatBonusOnAttribute", attribute="Speed", a=9, b=0, min="Rare",
                           name="Stormstride", desc="When Speed is contested, add +9."),
    "Surefooted":     dict(effect="FlatBonusOnAttribute", attribute="Speed", a=5, b=0, min="Common",
                           name="Surefooted", desc="When Speed is contested, add +5."),
    "Slaughtering":   dict(effect="FlatBonusOnAttribute", attribute="Power", a=5, b=0, min="Common",
                           name="Slaughtering", desc="When Power is contested, add +5."),
    "BulwarkOath":    dict(effect="PercentBonusWhenDefending", attribute="Power", a=12, b=0, min="Uncommon",
                           name="Bulwark Oath", desc="While defending, add 12% to the contested attribute."),
    "FirstCharge":    dict(effect="PercentBonusWhenLeading", attribute="Power", a=10, b=0, min="Uncommon",
                           name="First Charge", desc="While leading, add 10% to the contested attribute."),
    "ElderMemory":    dict(effect="WinsTiesOnAttribute", attribute="Age", a=0, b=0, min="Uncommon",
                           name="Elder Memory", desc="You win ties on Age."),
    "AncientBlood":   dict(effect="WinsTiesOnAttribute", attribute="Age", a=0, b=0, min="Common",
                           name="Ancient Blood", desc="You win ties on Age."),
    "TitanGirth":     dict(effect="PercentBonusOnAttribute", attribute="Height", a=14, b=0, min="Uncommon",
                           name="Titan Girth", desc="When Height is contested, add 14%."),
    "DeepRoots":      dict(effect="PercentBonusOnAttribute", attribute="Age", a=15, b=0, min="Common",
                           name="Deep Roots", desc="When Age is contested, add 15%."),
    "ColossalProwess": dict(effect="PercentBonusOnAttribute", attribute="Power", a=11, b=0, min="Uncommon",
                           name="Colossal Prowess", desc="When Power is contested, add 11%."),
    "Spellbreak":     dict(effect="NullifyOpponentAbilities", attribute="Power", a=0, b=0, min="Epic",
                           name="Spellbreak", desc="The opponent's abilities do nothing this round."),
    "Oathkeeper":     dict(effect="BonusPerFactionInOwnPile", attribute="Power", a=4, b=6, min="Rare",
                           name="Oathkeeper", desc="Add 4% per allied trophy in your pile, to 6 trophies."),
    "GiantSlayer":    dict(effect="BonusIfOpponentStatAbove", attribute="Height", a=18, b=300, min="Uncommon",
                           name="Giant-Slayer", desc="+18% when the opponent's Height is above 300 cm."),
    "BaneOfDragons":  dict(effect="BonusAgainstFaction", attribute="Power", a=16, b=0, min="Rare",
                           faction="Dragonkind", name="Dragon-Bane", desc="+16% against Dragonkind."),
    "BaneOfTheDead":  dict(effect="BonusAgainstFaction", attribute="Power", a=16, b=0, min="Rare",
                           faction="UndyingLegion", name="Death-Bane", desc="+16% against the Undying Legion."),
    "BaneOfTheAbyss": dict(effect="BonusAgainstFaction", attribute="Power", a=18, b=0, min="Epic",
                           faction="AbyssalHorde", name="Hell-Bane", desc="+18% against the Abyssal Horde."),
    "FeyTrickery":    dict(effect="WinIfMarginWithin", attribute="Power", a=7, b=0, min="Rare",
                           name="Fey Trickery", desc="When defending, lose by 7% or less and you win instead."),
    "HoardersGreed":  dict(effect="OnWinTakeDeckTop", attribute="Power", a=0, b=0, min="Epic",
                           name="Hoarder's Greed", desc="On a win, also take the top card of the deck."),
    "GraveRite":      dict(effect="OnWinForceExtraCapture", attribute="Power", a=0, b=0, min="Rare",
                           name="Grave-Rite", desc="On a win, the opponent also loses their weakest card."),
    "Undying":        dict(effect="OnLoseReturnToHandOnce", attribute="Power", a=0, b=0, min="Epic",
                           name="Undying", desc="Once per match, this card returns to your hand instead of being captured."),
    "HoardMagic":     dict(effect="PotScoreBonusOnWin", attribute="Power", a=2, b=0, min="Uncommon",
                           name="Hoard-Magic", desc="+2 score per pot card when you claim the pot."),
    "CursedRelic":    dict(effect="AlwaysPenalty", attribute="Power", a=-12, b=0, min="Common",
                           name="Cursed", desc="Subtract 12% from every attribute."),
    "Thickhide":      dict(effect="PercentBonusWhenDefending", attribute="Power", a=8, b=0, min="Common",
                           name="Thick Hide", desc="While defending, add 8% to the contested attribute."),
}

# ---------------------------------------------------------------------------
# The roster. (name, rarity, archetype, stat overrides, abilities, flavour)
# ---------------------------------------------------------------------------
CATALOG = {
    "dragonkind": [
        ("Ancient Red Wyrm", "Mythic", "elder", dict(age=11000, power=112, speed=46, height=2600),
         ["EmberFury", "HoardersGreed"], "She has slept on the same mountain of gold for nine thousand years."),
        ("Cinderwing Hatchling", "Common", "beast", dict(power=24, speed=71, height=95),
         ["Slaughtering"], "Angry, winged, and already counting your sheep."),
        ("Bog Green Drake", "Common", "brute", dict(height=340),
         ["Thickhide"], "Half swamp, half appetite."),
        ("Frostfang Wyrm", "Uncommon", "brute", dict(age=320, height=520),
         ["BulwarkOath"], "It freezes the lake, then sleeps on the ice."),
        ("Stormclad Wyvern", "Uncommon", "swift", dict(power=52, speed=79),
         ["Surefooted"], "Rides the front of every squall the coast fears."),
        ("Mud-Maw Whelp", "Common", "vermin", dict(power=18, speed=64, height=60),
         [], "A dragon by pedigree. A nuisance by size."),
        ("Ashmaiden Drake", "Rare", "swift", dict(power=68, speed=74, height=410),
         ["Stormstride", "FirstCharge"], "Burns the heretic first, asks the name later."),
        ("Vermilion Sky-Tyrant", "Rare", "titan", dict(power=74, speed=33, height=1450),
         ["TitanGirth"], "Its shadow is a county's worth of bad weather."),
        ("Hoarder of the Second Age", "Epic", "elder", dict(age=5400, power=88, height=1900),
         ["HoardMagic", "EmberFury"], "Two ages of tribute, none of it spent."),
        ("Elder Blue Tempest", "Legendary", "brute", dict(age=7200, power=101, speed=58, height=2100),
         ["ColossalProwess", "Spellbreak"], "Lightning is what it does while thinking."),
        ("Wyrm of the Broken Oath", "Epic", "titan", dict(power=84, speed=29, height=1750),
         ["GiantSlayer", "CursedRelic"], "Cursed to hunt every knight who ever lied to it."),
    ],
    "arcane": [
        ("Archmage of the Ninth Spire", "Legendary", "caster", dict(age=840, power=95, speed=64, height=185),
         ["Spellbreak", "FirstCharge"], "Nine spires, one tenure, zero patience."),
        ("Apprentice of the Blue Order", "Common", "balanced", dict(power=38, speed=54, age=19),
         [], "Borrowed a wand. Will not return it."),
        ("Hedge Witch of Fenwick", "Common", "caster", dict(power=44, speed=48, age=61),
         ["DeepRoots"], "Her poultices work. Her prices are obscene."),
        ("Clockwork Familiar", "Uncommon", "vermin", dict(power=34, speed=76, height=40),
         ["Surefooted"], "Wind it, and it files your paperwork."),
        ("Chronomancer of the Grey Hour", "Epic", "elder", dict(age=3100, power=79, speed=57),
         ["ElderMemory", "DeepRoots"], "Arrives precisely one minute before you need him."),
        ("Runescribe of the Fallen College", "Rare", "caster", dict(age=260, power=70),
         ["BulwarkOath"], "Every glyph is a promise the mountain remembers."),
        ("Pyromancer Duelist", "Uncommon", "swift", dict(power=59, speed=66),
         ["Slaughtering"], "Counts to two. Rarely gets to three."),
        ("Necrotheologian", "Rare", "caster", dict(age=410, power=68, speed=52),
         ["GraveRite"], "Wrote the funeral rites for things that never die."),
        ("Mirror Knight Errant", "Uncommon", "balanced", dict(power=57, speed=61, height=210),
         ["BulwarkOath"], "Fights you with your own reflexes, borrowed."),
        ("The Unbound Theurge", "Mythic", "caster", dict(age=6000, power=104, speed=71),
         ["Spellbreak", "HoardersGreed"], "Made a bargain with a god and won the paperwork."),
        ("Storm-Tower Magus", "Legendary", "brute", dict(age=520, power=93, speed=49, height=230),
         ["EmberFury", "TitanGirth"], "Channels the sky through a very expensive hat."),
    ],
    "blade": [
        ("Sworn Shield of the Dawn Gate", "Common", "holy", dict(power=48, speed=51, height=195),
         ["Thickhide"], "Twenty years on one wall. The wall thanks them occasionally."),
        ("Knight-Errant of the Silver Brake", "Common", "swift", dict(power=49, speed=63),
         ["Surefooted"], "Lost a joust, gained a song."),
        ("Battle Priest of the Ashen Rite", "Uncommon", "holy", dict(power=58, speed=52, age=44),
         ["BulwarkOath"], "Blesses the wound, then widens it."),
        ("Order Marshal", "Rare", "balanced", dict(power=69, speed=62, age=96),
         ["FirstCharge", "ElderMemory"], "Drills in the morning, buries in the afternoon."),
        ("Lancer of the Two-Bridges Guard", "Uncommon", "swift", dict(power=56, speed=70, height=205),
         [], "Never lost a bridge."),
        ("Grave-Warden Knight", "Rare", "brute", dict(power=71, speed=47, age=140),
         ["BaneOfTheDead"], "Sworn to keep what the legion wants back."),
        ("Paladin of the Broken Chain", "Epic", "holy", dict(power=86, speed=64, height=230),
         ["Spellbreak", "HoardersGreed"], "Freed ten thousand slaves and one demon, by accident."),
        ("Herald of the Last Muster", "Rare", "holy", dict(power=63, speed=59, age=88),
         ["Oathkeeper"], "Reads the names aloud. The line grows shorter."),
        ("War-Abbot of Ironvow", "Legendary", "brute", dict(power=96, speed=55, height=245),
         ["ColossalProwess", "GraveRite"], "Vowed silence in the eleventh year of the siege."),
        ("Duellist of the Ninth Hour", "Epic", "swift", dict(power=74, speed=92),
         ["FeyTrickery"], "Wins on the last step of a very long argument."),
        ("The Oath That Walks", "Mythic", "holy", dict(age=12000, power=103, speed=68, height=290),
         ["Undying", "ElderMemory"], "A vow so old it grew armour and started walking."),
    ],
    "ironhold": [
        ("Deep Delver Sergeant", "Common", "brute", dict(power=52, speed=44, height=140),
         ["Thickhide"], "Three feet of dwarf, forty feet of grudges."),
        ("Runesmith of the Ninth Forge", "Uncommon", "balanced", dict(power=58, speed=45, height=150),
         ["BulwarkOath"], "Hammers blessings into steel while they are still hot."),
        ("Anvil-Brawler", "Common", "brute", dict(power=57, speed=41, height=145),
         ["Slaughtering"], "Argues with metal. Metal loses."),
        ("Stonebridge Warden", "Rare", "titan", dict(power=72, speed=32, height=760),
         ["TitanGirth", "BulwarkOath"], "Holds the bridge. Has held it for a while."),
        ("Golem of the Hollow Vault", "Rare", "titan", dict(power=76, speed=26, height=980),
         ["TitanGirth"], "Doors, but very slowly and with great opinion."),
        ("Forge-Titan Kurnold", "Epic", "titan", dict(power=89, speed=24, height=1600),
         ["ColossalProwess", "Spellbreak"], "Anvils its hammer on the mountain, for practice."),
        ("Grudge-Keeper of the Long Hall", "Legendary", "elder", dict(age=1400, power=94, speed=38, height=170),
         ["ElderMemory", "DeepRoots"], "Four centuries of wrongs, alphabetised."),
        ("Boulder-Shaped Berserker", "Uncommon", "beast", dict(power=62, speed=52, height=190),
         ["FirstCharge"], "Rolls downhill. Calls it tactics."),
        ("Gilded Vault Warden", "Epic", "brute", dict(power=83, speed=42, height=200),
         ["HoardMagic", "HoardersGreed"], "Paid in coin, guarding coin, counting coin."),
        ("Steam-Maul Engineer", "Rare", "balanced", dict(power=68, speed=55, height=155),
         ["Stormstride"], "Her machine works. Do not ask about the noise."),
        ("The First Ancestor", "Mythic", "titan", dict(age=21000, power=106, speed=22, height=2200),
         ["Undying", "TitanGirth"], "Carved before mountains agreed to stay put."),
    ],
    "fey": [
        ("Sprite of the Dew Market", "Common", "vermin", dict(power=21, speed=84, height=25),
         ["Surefooted"], "Sells dew. Delivers it before you agree."),
        ("Thorn-Riding Piskie", "Common", "swift", dict(power=36, speed=78, height=70),
         [], "Steals buttons, then the regiment."),
        ("Hedge-Knight of the Green March", "Uncommon", "balanced", dict(power=54, speed=68, height=175),
         ["BulwarkOath"], "Chivalry, but the clauses favour him."),
        ("Fae of the Ninefold Name", "Rare", "caster", dict(age=900, power=66, speed=63),
         ["ElderMemory"], "Tell it your name and it owns the second syllable."),
        ("Court Dancer, Unfinished", "Rare", "swift", dict(power=64, speed=88),
         ["FeyTrickery", "Stormstride"], "Her solo has lasted three human generations."),
        ("Oberon's Hounds", "Epic", "beast", dict(power=81, speed=90),
         ["FirstCharge"], "They do not chase. They arrive."),
        ("Grinning Hollow Man", "Uncommon", "balanced", dict(power=52, speed=59, height=215),
         ["CursedRelic"], "No face, all expression."),
        ("Wisp Warden", "Common", "vermin", dict(power=26, speed=74, height=45),
         ["DeepRoots"], "Carries lanterns; is the lantern."),
        ("The Autumn Queen", "Legendary", "holy", dict(age=3000, power=90, speed=66, height=215),
         ["Spellbreak", "Oathkeeper"], "Every deal she offers is fair. Twice."),
        ("Briar Colossus", "Epic", "titan", dict(power=86, speed=28, height=1300),
         ["TitanGirth", "Thickhide"], "A hedge, technically. A catastrophe, practically."),
        ("Twelfth-Night Trickster", "Mythic", "swift", dict(age=8000, power=99, speed=104),
         ["FeyTrickery", "HoardersGreed"], "Keeps the last hour of every year as a spare."),
    ],
    "undying": [
        ("Bone Sentry of the Low Gate", "Common", "undead", dict(power=45, speed=42, height=185),
         ["Thickhide"], "Twenty lifetimes on night shift."),
        ("Wailing Wraith", "Common", "swift", dict(power=41, speed=66, height=205),
         ["DeepRoots"], "Loudest at three in the morning, always."),
        ("Grave-Touched Ghoul", "Uncommon", "beast", dict(power=61, speed=58),
         ["Slaughtering"], "Digs with a courtesy it does not extend."),
        ("Crypt Bishop", "Uncommon", "caster", dict(power=55, speed=47, height=190),
         ["HoardMagic"], "Reads last rites over the wrong books."),
        ("Vampire of the Pale Waltz", "Rare", "swift", dict(age=760, power=68, speed=76),
         ["FeyTrickery", "ElderMemory"], "Never ages, always arrives late, never wrong."),
        ("Skeleton Chorus", "Rare", "horde", dict(power=64, speed=54, height=180),
         ["AncientBlood"], "Perfect harmony, no lungs."),
        ("Bog Revenant", "Epic", "undead", dict(age=1900, power=84, speed=41, height=240),
         ["Undying", "BulwarkOath"], "Drowned twice. Found both times."),
        ("Lich of the Sunless Crown", "Legendary", "caster", dict(age=4300, power=97, speed=52),
         ["Spellbreak", "GraveRite"], "His phylactery is in the bank. In escrow. Interest accruing."),
        ("Plague Heralds", "Rare", "caster", dict(power=66, speed=59),
         ["GraveRite"], "Cleared the city three days before the bells."),
        ("The Rotting Colossus", "Epic", "titan", dict(power=88, speed=25, height=1500),
         ["TitanGirth", "CursedRelic"], "A siege that forgot to stop walking."),
        ("First Lich, Last Silence", "Mythic", "elder", dict(age=999999, power=105, speed=37),
         ["Undying", "Spellbreak"], "He remembered death before it had a name."),
    ],
    "abyss": [
        ("Hellhound Pup", "Common", "beast", dict(power=48, speed=74, height=90),
         ["Slaughtering"], "Chews boots, then the leg they were on."),
        ("Pit Brute", "Common", "brute", dict(power=56, speed=43, height=230),
         [], "Subtlety is a luxury of the upper spheres."),
        ("Contract Imp", "Uncommon", "vermin", dict(power=33, speed=81, height=55),
         ["Surefooted", "CursedRelic"], "Reads the fine print aloud. Always wins."),
        ("Barbed Duelist", "Rare", "swift", dict(power=70, speed=72, height=200),
         ["FirstCharge"], "Bleeds on the floor and calls it a concession."),
        ("Horned Siege Fiend", "Rare", "titan", dict(power=78, speed=31, height=950),
         ["TitanGirth", "BaneOfDragons"], "Breaks walls the way dragons break habits."),
        ("Ashfiend Marauder", "Uncommon", "brute", dict(power=63, speed=57),
         ["Slaughtering"], "Burns the ledger and the accountant."),
        ("Duke of the Ninth Cage", "Epic", "caster", dict(age=7000, power=87, speed=61),
         ["GraveRite", "BulwarkOath"], "Rules a prison he was told is a palace."),
        ("Devourer of Names", "Legendary", "brute", dict(power=98, speed=59),
         ["Spellbreak", "FeyTrickery"], "Eat the name, keep the debts."),
        ("Chain-Iron Colossus", "Epic", "titan", dict(power=91, speed=23, height=1450),
         ["TitanGirth", "Oathkeeper"], "Dragged a mountain chain out of the pit, as a joke."),
        ("Whisper of the Seventh Gate", "Rare", "swift", dict(power=66, speed=84),
         ["DeepRoots"], "Repeats your secrets, but slightly wrong."),
        ("The Unbound Archfiend", "Mythic", "brute", dict(age=19000, power=114, speed=49),
         ["Undying", "HoardersGreed"], "Escaped once. Regretted it. Escaped again."),
    ],
    "celestial": [
        ("Dawn Sentry", "Common", "holy", dict(power=47, speed=57, height=205),
         ["Thickhide"], "Never misses a sunrise. Has opinions about it."),
        ("Cloudlight Aerial", "Uncommon", "swift", dict(power=53, speed=80),
         ["Surefooted"], "Fights in the third dimension; everyone else in two."),
        ("Storm Colossus", "Rare", "titan", dict(power=77, speed=30, height=1800),
         ["TitanGirth", "EmberFury"], "Walks on thunder out of politeness."),
        ("Seraph of the Seven Trumps", "Epic", "holy", dict(power=85, speed=69),
         ["Spellbreak", "FirstCharge"], "Six trumpets are a warning. The seventh is the order."),
        ("Justice Herald", "Uncommon", "balanced", dict(power=59, speed=60),
         ["BulwarkOath"], "Reads the charge, then passes the sentence."),
        ("Gale Rider", "Common", "swift", dict(power=42, speed=77),
         [], "Delivers verdicts and messages, mostly verdicts."),
        ("Astral Dragon-Slain", "Rare", "holy", dict(power=73, speed=65),
         ["BaneOfDragons"], "A saint with a very specific résumé."),
        ("Throne Warden", "Epic", "titan", dict(power=88, speed=27, height=1150),
         ["TitanGirth", "HoardMagic"], "Has not blinked since the second age."),
        ("Solar Archon", "Legendary", "holy", dict(age=5000, power=99, speed=72),
         ["HoardersGreed", "ColossalProwess"], "His light is a legal document."),
        ("Choir of Quiet Wings", "Uncommon", "balanced", dict(power=56, speed=63),
         ["ElderMemory"], "Sings the wounded to sleep, and the tired further on."),
        ("The Morning That Judges", "Mythic", "elder", dict(age=30000, power=110, speed=66, height=450),
         ["ElderMemory", "Spellbreak"], "Arrives at the end of every story, on time."),
    ],
    "beastwild": [
        ("Goblin Knifer", "Common", "vermin", dict(power=30, speed=72, height=95),
         ["Surefooted"], "Six of him is a war party."),
        ("Warg Rider", "Uncommon", "beast", dict(power=57, speed=76),
         ["FirstCharge"], "Two appetites, one direction."),
        ("Orc War Drummer", "Common", "brute", dict(power=54, speed=48, height=210),
         ["Thickhide"], "Sets the pace. The pace is violence."),
        ("Skinchanger of the Long Winter", "Rare", "balanced", dict(power=67, speed=68),
         ["DeepRoots"], "Wears three shapes and a grudge."),
        ("Werewolf Alpha", "Epic", "beast", dict(power=86, speed=88),
         ["Undying"], "The full moon is a formality."),
        ("Troll of the Grey Ford", "Uncommon", "titan", dict(power=64, speed=34, height=620),
         ["TitanGirth", "BulwarkOath"], "Regrows an argument, and an arm."),
        ("Cave Ogre", "Rare", "brute", dict(power=76, speed=38, height=420),
         ["ColossalProwess"], "Clubs, then improvises with the club."),
        ("Bog Hag of the Fen-Mother", "Rare", "caster", dict(age=600, power=68, speed=52),
         ["GraveRite", "CursedRelic"], "Curses are her only inheritance."),
        ("Mantikor Prime", "Legendary", "beast", dict(power=97, speed=83),
         ["Stormstride", "Spellbreak"], "Lion, scorpion, and a very bad temper."),
        ("Goblin Saboteur", "Common", "vermin", dict(power=28, speed=79, height=88),
         [], "Tunnels under the siege, out the other side of the war."),
        ("The Long Winter's Son", "Mythic", "beast", dict(age=4000, power=109, speed=91),
         ["GiantSlayer", "Undying"], "Winter's only heir, and he is early."),
    ],
    "deepwater": [
        ("Tidepool Scout", "Common", "swift", dict(power=40, speed=72, height=110),
         ["Surefooted"], "Small, salt, everywhere."),
        ("Merrow Spearwife", "Common", "balanced", dict(power=49, speed=61, height=180),
         [], "Trades surface trinkets for surface secrets."),
        ("Reef Lurker", "Uncommon", "brute", dict(power=60, speed=45, height=260),
         ["Thickhide"], "Ambush is a tide like any other."),
        ("Sharkwere of the Brine Moon", "Rare", "beast", dict(power=71, speed=86),
         ["FirstCharge", "GiantSlayer"], "Half sailor, half fin, all grudge."),
        ("Kraken of the Trench Throne", "Legendary", "titan", dict(power=100, speed=35, height=3200),
         ["TitanGirth", "HoardersGreed"], "Nine arms, nine ledgers, no forgiveness."),
        ("Drowned King", "Epic", "undead", dict(age=2400, power=84, speed=44, height=230),
         ["ElderMemory", "Undying"], "Rules a kingdom of silt and receipts."),
        ("Sea Serpent of the Cold Vein", "Epic", "titan", dict(power=87, speed=48, height=2600),
         ["DeepRoots", "TitanGirth"], "Twelve miles long, according to the sailors who survived."),
        ("Pearlbound Oracle", "Uncommon", "caster", dict(age=520, power=52, speed=46),
         ["DeepRoots"], "Speaks only in tides. Always right, always late."),
        ("Coral Golem", "Rare", "titan", dict(power=74, speed=22, height=680),
         ["TitanGirth", "BulwarkOath"], "A reef that decided to walk."),
        ("Abyssal Siren", "Rare", "swift", dict(power=65, speed=79),
         ["FeyTrickery"], "Her song has a clause."),
        ("The Tide That Keeps", "Mythic", "elder", dict(age=16000, power=107, speed=58, height=900),
         ["HoardMagic", "Spellbreak"], "It takes the ships and keeps the names."),
    ],
}
